### ISSUE TITLE
Project and settings are deleted after reboot addon

### ISSUE THREAD

**Issue by cscherpenisse** [SmartLiving-Rocks/FUXA_HomeAssistant_Addon#2]
After rebooting the addon, the project and all settings are deleted.
Doesn't the addon save this automatically?

**Comment by SmartLiving-Rocks** [comment]
I have a workaround described here:
https://github.com/frangoteam/FUXA/issues/1138#issuecomment-2029482013

I have the creator of Fuxa asked to develop the add-on for Home Assistant because of this issue.
